### ISSUE TITLE
mp_calc/evaluate expression jupyter notebook improvements

### ISSUE THREAD

**Issue by zackteo** [kurniawano/d2w_mini_projects#2]
I realised my tests didn't pass but I was unfamiliar with jupyter notebook ><
In[*] <--- means the code is still running - I thought since i clicked through, that means the code passed already 

That being said I think it can be very misleading

```py
expr2 = EvaluateExpression("(1+2 *4-  3)* (7/5 * 6)")
assert expr2.evaluate() == 36 #3rd test
```
Based on the instructions is possible to iterate through `self.expr` directly which will likely cause issues. It will look like when you finally pass the first 2 cases, then 3rd case which causes the [*] may appear like you also passed

```py
expression = self.insert_space()
tokens = expression.split()
```
I propose that we could mention the need to do this (below) somewhere in the instructions! And perhaps just a note to students unfamiliar to jupyter like me that [*] doesn't mean pass ><

**Comment by kurniawano** [comment]
@zackteo , what do you mean by to iterate through `self.expr` directly? `self.expr` is the string containing the expression. Do you mean that students do not follow the algorithm using the stacks?

So you also suggest to add two notes:
- one is to call `insert_space()` and `split()` the string into tokens
- the other is a note to tell students [*] means it is still running

is that right?

**Comment by zackteo** [comment]
@kurniawano Yeap, the string containing the expression. Instead of what you had intended for - to `insert_space()` and then `split()` the strings into tokens. I guess it could be still possible but then they would need to handle the spaces separately - so I'm not sure if you would want to explicitly point out to students that they made `insert_space()` for a reason

Everything could still potentially be the same just that it becomes 
```py
operand_stack = Stack()
operator_stack = Stack()
for item in self.expr:
```
Just that I think figuring out why there's isn't working might prove to be a pain point regarding the spaces

And yeap `[*]` for running - maybe it is just me, not being too attentive to it but I think I might confuse students to think they are done like me

**Comment by kurniawano** [comment]
@zackteo , right, I add the following in the template to make sure students use those methods.

```
operand_stack = Stack()
operator_stack = Stack()
expression = self.insert_space()
tokens = expression.split()
```
