### ISSUE TITLE
Troubleshooting section?

### ISSUE THREAD

**Issue by zackteo** [kurniawano/d2w_mini_projects#3]
Should we include a section that includes stuff like
1. `ModuleNotFoundError: No module named 'flask_bootstrap'`? Or just can't run flask/use transcrypt?
- Are you in your virtualenv ? `source virtenv/bin/activate`
2. The app doesn't change even though I make changes to the code?!?
- If you made changes to files in `app/static`
Did you run `python -m transcrypt -b target.py` <-- target being file you are transpiling
- What you want is hot-reloading 
You can run `export FLASK_ENV=development` before `flask run`
or `flask run --reload --debugger`

**Comment by kurniawano** [comment]
@zackteo , Your suggestion is to add a "troubleshooting" section in the notes containing these two points?

**Comment by zackteo** [comment]
@kurniawano Yeap! I'm not sure what's your thoughts about it - but I thought an FAQ section of sorts would be good - else we might have a lot of students who get stuck on similar issues

**Comment by kurniawano** [comment]
@zackteo , I have added those two points at the end.
